services:
  tinyauth:
    image: ghcr.io/steveiliop56/tinyauth:v3
    container_name: tinyauth
    restart: unless-stopped
    environment:
      - SECRET=${SECRET}
      - APP_URL=https://tinyauth.tahamjp.github.io/DoorFactory/
      - USERS_FILE=users_file
      - LOG_LEVEL=0
    volumes:
      - ./users_file:/TinyAuth/users_file
    networks:
      - proxy
    labels:
      traefik.enable: true
      traefik.http.routers.tinyauth.rule: Host(`https://tinyauth.tahamjp.github.io/DoorFactory/`)
      traefik.http.middlewares.tinyauth.forwardauth.address: http://tinyauth:3000/api/auth/traefik
  networks:
    proxy:
      external: true
